// Generated by scripts/process-inverter-data.ts
// Source: inverter daily data 2022-12 – 2026-01 (~3 years), reference installation
// All values are averages across all available years for that calendar month.

/** Average kWh produced by the PV system per day, by month (index 0 = January). */
export const avgDailyProductionByMonth: number[] = [4, 11.2, 25.5, 50, 68.8, 67.8, 58.8, 47.5, 34.9, 17, 6.6, 2.8];

/** Average kWh consumed by the household per day, by month (index 0 = January).
 *  Includes both grid import and solar self-consumption. Source: inverter metering. */
export const avgDailyConsumptionByMonth: number[] = [48.7, 51.6, 45.2, 51.3, 21.7, 18, 22.3, 19.2, 19.2, 27.2, 41.9, 41.5];

/** Ratio of actual daily production to the GHI-based model estimate, by month.
 *  The model (GHI × kWp × PR) consistently underestimates — worst in spring/fall
 *  (+34–43%) because tilted panels capture low-angle sun more efficiently than
 *  horizontal irradiance implies. Multiply ghiToKwh() output by this factor.
 *  Generated by scripts/build-solar-calibration.ts (added 2026-07-10) from
 *  avgDailyProductionByMonth above and lib/irradiance-data.ts's climatology — re-run it after
 *  regenerating either of those for a new site. See DOMAIN.md's "Adapting to a new site"
 *  section for the full onboarding order. */
export const solarCalibrationByMonth: number[] = [1.13, 1.21, 1.21, 1.37, 1.38, 1.26, 1.16, 1.20, 1.34, 1.38, 1.43, 1.21];

// ── Weather-aware daily load model ───────────────────────────────────────────
// Fitted by scripts/build-load-model.mjs over 1141 days (2022-12-06..2026-01-19):
// daily total household consumption (from the solar-data/*.xlsx plant reports)
// regressed against Open-Meteo ERA5 daily mean temperature.
//
//   load_day = avgDailyConsumptionByMonth[m]
//            + LOAD_SLOPE_KWH_PER_HDD × (HDD − hddNormalByMonth[m])
//   HDD = max(0, HDD_T_BASE_C − dailyMeanTemp°C)
//
// The monthly average is kept as the LEVEL (it captures non-temperature
// seasonality the regression can't — e.g. the April plateau) and temperature
// only adds a within-month heating adjustment, which self-zeroes in summer
// because HDD ≈ hddNormal ≈ 0 there. Within-R² is low (~0.14): daily load is
// dominated by non-temperature factors, so this refines the seasonal baseline
// for cold/warm spells rather than predicting any given day precisely.
export const HDD_T_BASE_C = 13;

/** Extra kWh/day per heating-degree-day above the month's normal HDD. */
export const LOAD_SLOPE_KWH_PER_HDD = 2.59;

/** Climatological mean HDD per day for each month (index 0 = January), base 13 °C. */
export const hddNormalByMonth: number[] = [12.3, 11.1, 9.3, 5.6, 1.4, 0.2, 0, 0, 0.4, 3.3, 8.4, 10.4];
