// Generated by scripts/tools/process-inverter-data.ts
// Source: inverter daily data 2022-12 – 2026-01 (~3 years), reference installation
// All values are averages across all available years for that calendar month.

/** Average kWh produced by the PV system per day, by month (index 0 = January). */
export const avgDailyProductionByMonth: number[] = [4, 11.2, 25.5, 50, 68.8, 67.8, 58.8, 47.5, 34.9, 17, 6.6, 2.8];

/** Average kWh consumed by the household per day, by month (index 0 = January).
 *  Includes both grid import and solar self-consumption. Source: the Ellevio-corrected
 *  daily series (scripts/tools/build-corrected-consumption.py, 2022-05-19..2026-01-19) — the raw
 *  plant reports' first winter under-read consumption by ~half (old inverter meter
 *  misconfig, physically impossible vs the billing meter; found 2026-07-11), which had
 *  dragged Jan/Feb/Dec ~7-13% low in the previous values. */
export const avgDailyConsumptionByMonth: number[] = [55.2, 54.1, 42.6, 51.4, 22.4, 19, 21.6, 19.5, 18.6, 24.1, 39.9, 44.6];

/** Ratio of actual daily production to the GHI-based model estimate, by month.
 *  The model (GHI × kWp × PR) consistently underestimates — worst in spring/fall
 *  (+34–43%) because tilted panels capture low-angle sun more efficiently than
 *  horizontal irradiance implies. Multiply ghiToKwh() output by this factor.
 *  Generated by scripts/tools/build-solar-calibration.ts (added 2026-07-10) from
 *  avgDailyProductionByMonth above and lib/irradiance-data.ts's climatology — re-run it after
 *  regenerating either of those for a new site. See DOMAIN.md's "Adapting to a new site"
 *  section for the full onboarding order. */
export const solarCalibrationByMonth: number[] = [1.13, 1.21, 1.21, 1.37, 1.38, 1.26, 1.16, 1.20, 1.34, 1.38, 1.43, 1.21];

// ── Weather-aware daily load model ───────────────────────────────────────────
// Fitted by scripts/tools/build-load-model.mjs over 1342 days (2022-05-19..2026-01-19) of the
// Ellevio-corrected daily consumption series (see avgDailyConsumptionByMonth above and
// scripts/tools/build-corrected-consumption.py), regressed against Open-Meteo ERA5 daily mean
// temperature. Refitted 2026-07-11: within-R²=0.170, RMSE=14.6 kWh/day (was 0.144/17.5 on
// the partly-broken raw plant data).
//
//   load_day = avgDailyConsumptionByMonth[m]
//            + LOAD_SLOPE_KWH_PER_HDD × (HDD − hddNormalByMonth[m])
//   HDD = max(0, HDD_T_BASE_C − dailyMeanTemp°C)
//
// The monthly average is kept as the LEVEL (it captures non-temperature
// seasonality the regression can't — e.g. the April plateau) and temperature
// only adds a within-month heating adjustment, which self-zeroes in summer
// because HDD ≈ hddNormal ≈ 0 there. Within-R² is low (~0.17): daily load is
// dominated by non-temperature factors, so this refines the seasonal baseline
// for cold/warm spells rather than predicting any given day precisely.
export const HDD_T_BASE_C = 13;

/** Extra kWh/day per heating-degree-day above the month's normal HDD. */
export const LOAD_SLOPE_KWH_PER_HDD = 2.49;

/** Climatological mean HDD per day for each month (index 0 = January), base 13 °C. */
export const hddNormalByMonth: number[] = [12.3, 11.1, 9.3, 5.6, 1.4, 0.2, 0, 0, 0.5, 3, 7.8, 10.5];

// ── Measured intraday load shape ─────────────────────────────────────────────
// Share of the day's total consumption falling in each local hour (rows: month 1-12,
// index 0 = January; columns: hour 0-23; each row sums to 1). Generated by
// scripts/tools/build-intraday-profile.py (2026-07-11) from the Ellevio billing-meter history —
// TRUE load, not the night-tariff-distorted series that forced the old uniform split:
// each month uses only its clean window (winters Nov-Feb 2022-2025 where PV is negligible
// and the Jan-2026 battery didn't exist yet; other months from the pre-PV year). Only Jan,
// Feb, Oct, Nov and Dec still come from it; every other month is now measured, see below.
//
// JULY and AUGUST are different: they come from the house's OWN measured house_load_w (30 and
// 31 complete days of telemetry, --telemetry-months 7,8) rather than the meter history,
// because the only clean meter window for them is pre-PV, pre-battery behaviour. On the
// reference deployment the refresh moved real weight: the evening 17-21 block dropped from
// 29.4% to 23.4% (July) and 29.0% to 24.3% (August), the old 18h spike disappeared, and the
// peak landed at 16h in both months, with midday up ~10%. Two independent months agreeing in
// direction and size is the reason to believe it, and the daily TOTAL barely moved (July
// 19.4 -> 20.9, August 20.3 -> 20.3 kWh/day) — the level was right, the shape was not. The
// likely reading, as interpretation rather than measurement: discretionary load has migrated
// into the solar-rich afternoon and away from the pre-PV dinner peak. SEPTEMBER followed the
// same way (29 complete days, --telemetry-months 7,8,9): evening 17-21 27.1% -> 24.2%, peak
// again at 16h. JUNE was rebuilt the same way from the inverter's own 5-minute history in
// the vendor cloud (27 days; evening 27.6% -> 25.3%, peak 16h). MARCH, APRIL and MAY combine
// the inverter's AC output with the billing meter's import and export (the inverter's own
// grid meter was mis-wired before June on the reference deployment): April is measured for
// the first time instead of interpolated, March's midday trough rises from 1.1% to 3.3%, and
// May's peak moves 18h -> 16h. February stays on three winters of meter history rather than
// one battery-era winter that disagrees with it. Expect your own site to
// differ; regenerate rather than inheriting these.
//
// Winter shape: morning (06-07) and
// evening (16-18) peaks ~5-6%/h, midday trough ~2-2.5%/h — the uniform 4.17%/h assumption
// under-allocated load at exactly the price-peak hours by ~30-40%. October's extreme
// midday trough rests on a single pre-PV month (31 days) — noisier than the winter rows
// (85-124 days each), but shoulder-month stakes are low.
export const hourShareByMonth: number[][] = [
  [0.0465, 0.0468, 0.0474, 0.0474, 0.0465, 0.0460, 0.0519, 0.0531, 0.0421, 0.0335, 0.0273, 0.0236, 0.0251, 0.0251, 0.0297, 0.0429, 0.0526, 0.0513, 0.0472, 0.0406, 0.0414, 0.0407, 0.0440, 0.0474],
  [0.0485, 0.0466, 0.0457, 0.0475, 0.0472, 0.0467, 0.0569, 0.0549, 0.0473, 0.0370, 0.0279, 0.0245, 0.0198, 0.0170, 0.0241, 0.0293, 0.0439, 0.0579, 0.0521, 0.0444, 0.0438, 0.0410, 0.0467, 0.0493],
  [0.0345, 0.0359, 0.0357, 0.0369, 0.0416, 0.0441, 0.0571, 0.0636, 0.0534, 0.0414, 0.0382, 0.0389, 0.0377, 0.0366, 0.0333, 0.0363, 0.0594, 0.0453, 0.0406, 0.0392, 0.0400, 0.0391, 0.0343, 0.0370],
  [0.0307, 0.0341, 0.0360, 0.0389, 0.0400, 0.0414, 0.0633, 0.0678, 0.0503, 0.0433, 0.0408, 0.0407, 0.0450, 0.0406, 0.0364, 0.0338, 0.0536, 0.0477, 0.0398, 0.0368, 0.0420, 0.0371, 0.0299, 0.0296],
  [0.0233, 0.0240, 0.0255, 0.0255, 0.0280, 0.0348, 0.0544, 0.0493, 0.0441, 0.0438, 0.0399, 0.0537, 0.0552, 0.0532, 0.0446, 0.0418, 0.0733, 0.0575, 0.0452, 0.0421, 0.0446, 0.0389, 0.0307, 0.0270],
  [0.0258, 0.0263, 0.0248, 0.0257, 0.0265, 0.0284, 0.0412, 0.0486, 0.0459, 0.0441, 0.0431, 0.0506, 0.0459, 0.0431, 0.0433, 0.0462, 0.0629, 0.0607, 0.0573, 0.0482, 0.0439, 0.0433, 0.0390, 0.0350],
  [0.0267, 0.0271, 0.0263, 0.0261, 0.0266, 0.0276, 0.0309, 0.0435, 0.0473, 0.0447, 0.0454, 0.0514, 0.0472, 0.0505, 0.0498, 0.0499, 0.0750, 0.0632, 0.0465, 0.0415, 0.0422, 0.0404, 0.0378, 0.0326],
  [0.0243, 0.0233, 0.0246, 0.0236, 0.0238, 0.0254, 0.0360, 0.0436, 0.0488, 0.0446, 0.0470, 0.0591, 0.0552, 0.0509, 0.0474, 0.0489, 0.0662, 0.0660, 0.0458, 0.0484, 0.0443, 0.0387, 0.0327, 0.0312],
  [0.0231, 0.0236, 0.0249, 0.0264, 0.0274, 0.0272, 0.0483, 0.0445, 0.0544, 0.0509, 0.0481, 0.0506, 0.0498, 0.0437, 0.0436, 0.0431, 0.0735, 0.0621, 0.0498, 0.0495, 0.0455, 0.0346, 0.0278, 0.0274],
  [0.0381, 0.0431, 0.0440, 0.0425, 0.0465, 0.0522, 0.0870, 0.0776, 0.0483, 0.0206, 0.0130, 0.0108, 0.0106, 0.0028, 0.0084, 0.0230, 0.0346, 0.0654, 0.0911, 0.0679, 0.0509, 0.0412, 0.0401, 0.0402],
  [0.0426, 0.0427, 0.0428, 0.0445, 0.0472, 0.0506, 0.0594, 0.0575, 0.0472, 0.0318, 0.0237, 0.0214, 0.0221, 0.0226, 0.0305, 0.0427, 0.0617, 0.0631, 0.0490, 0.0407, 0.0397, 0.0350, 0.0383, 0.0432],
  [0.0468, 0.0472, 0.0515, 0.0478, 0.0474, 0.0505, 0.0525, 0.0487, 0.0404, 0.0360, 0.0308, 0.0290, 0.0261, 0.0277, 0.0331, 0.0414, 0.0504, 0.0511, 0.0454, 0.0359, 0.0363, 0.0365, 0.0415, 0.0459],
];
