// Generated by scripts/tools/process-inverter-data.ts
// Source: inverter daily data 2022-12 – 2026-01 (~3 years), reference installation
// All values are averages across all available years for that calendar month.

/** Average kWh produced by the PV system per day, by month (index 0 = January). */
export const avgDailyProductionByMonth: number[] = [4, 11.2, 25.5, 50, 68.8, 67.8, 58.8, 47.5, 34.9, 17, 6.6, 2.8];

/** Average kWh consumed by the household per day, by month (index 0 = January).
 *  Includes both grid import and solar self-consumption. Source: the Ellevio-corrected
 *  daily series (scripts/tools/build-corrected-consumption.py, 2022-05-19..2026-01-19) — the raw
 *  plant reports' first winter under-read consumption by ~half (old inverter meter
 *  misconfig, physically impossible vs the billing meter; found 2026-07-11), which had
 *  dragged Jan/Feb/Dec ~7-13% low in the previous values. */
export const avgDailyConsumptionByMonth: number[] = [55.2, 54.1, 42.6, 51.4, 22.4, 19, 21.6, 19.5, 18.6, 24.1, 39.9, 44.6];

/** Ratio of actual daily production to the GHI-based model estimate, by month.
 *  The model (GHI × kWp × PR) consistently underestimates — worst in spring/fall
 *  (+34–43%) because tilted panels capture low-angle sun more efficiently than
 *  horizontal irradiance implies. Multiply ghiToKwh() output by this factor.
 *  Generated by scripts/tools/build-solar-calibration.ts (added 2026-07-10) from
 *  avgDailyProductionByMonth above and lib/irradiance-data.ts's climatology — re-run it after
 *  regenerating either of those for a new site. See DOMAIN.md's "Adapting to a new site"
 *  section for the full onboarding order. */
export const solarCalibrationByMonth: number[] = [1.13, 1.21, 1.21, 1.37, 1.38, 1.26, 1.16, 1.20, 1.34, 1.38, 1.43, 1.21];

// ── Weather-aware daily load model ───────────────────────────────────────────
// Fitted by scripts/tools/build-load-model.mjs over 1342 days (2022-05-19..2026-01-19) of the
// Ellevio-corrected daily consumption series (see avgDailyConsumptionByMonth above and
// scripts/tools/build-corrected-consumption.py), regressed against Open-Meteo ERA5 daily mean
// temperature. Refitted 2026-07-11: within-R²=0.170, RMSE=14.6 kWh/day (was 0.144/17.5 on
// the partly-broken raw plant data).
//
//   load_day = avgDailyConsumptionByMonth[m]
//            + LOAD_SLOPE_KWH_PER_HDD × (HDD − hddNormalByMonth[m])
//   HDD = max(0, HDD_T_BASE_C − dailyMeanTemp°C)
//
// The monthly average is kept as the LEVEL (it captures non-temperature
// seasonality the regression can't — e.g. the April plateau) and temperature
// only adds a within-month heating adjustment, which self-zeroes in summer
// because HDD ≈ hddNormal ≈ 0 there. Within-R² is low (~0.17): daily load is
// dominated by non-temperature factors, so this refines the seasonal baseline
// for cold/warm spells rather than predicting any given day precisely.
export const HDD_T_BASE_C = 13;

/** Extra kWh/day per heating-degree-day above the month's normal HDD. */
export const LOAD_SLOPE_KWH_PER_HDD = 2.49;

/** Climatological mean HDD per day for each month (index 0 = January), base 13 °C. */
export const hddNormalByMonth: number[] = [12.3, 11.1, 9.3, 5.6, 1.4, 0.2, 0, 0, 0.5, 3, 7.8, 10.5];

// ── Measured intraday load shape ─────────────────────────────────────────────
// Share of the day's total consumption falling in each local hour (rows: month 1-12,
// index 0 = January; columns: hour 0-23; each row sums to 1). Generated by
// scripts/tools/build-intraday-profile.py (2026-07-11) from the Ellevio billing-meter history —
// TRUE load, not the night-tariff-distorted series that forced the old uniform split:
// each month uses only its clean window (winters Nov-Feb 2022-2025 where PV is negligible
// and the Jan-2026 battery didn't exist yet; other months from the pre-PV year; April
// interpolated Mar/May — no clean April exists). Winter shape: morning (06-07) and
// evening (16-18) peaks ~5-6%/h, midday trough ~2-2.5%/h — the uniform 4.17%/h assumption
// under-allocated load at exactly the price-peak hours by ~30-40%. October's extreme
// midday trough rests on a single pre-PV month (31 days) — noisier than the winter rows
// (85-124 days each), but shoulder-month stakes are low.
export const hourShareByMonth: number[][] = [
  [0.0465, 0.0468, 0.0474, 0.0474, 0.0465, 0.0460, 0.0519, 0.0531, 0.0421, 0.0335, 0.0273, 0.0236, 0.0251, 0.0251, 0.0297, 0.0429, 0.0526, 0.0513, 0.0472, 0.0406, 0.0414, 0.0407, 0.0440, 0.0474],
  [0.0485, 0.0466, 0.0457, 0.0475, 0.0472, 0.0467, 0.0569, 0.0549, 0.0473, 0.0370, 0.0279, 0.0245, 0.0198, 0.0170, 0.0241, 0.0293, 0.0439, 0.0579, 0.0521, 0.0444, 0.0438, 0.0410, 0.0467, 0.0493],
  [0.0564, 0.0572, 0.0598, 0.0567, 0.0542, 0.0606, 0.0770, 0.0547, 0.0350, 0.0196, 0.0162, 0.0162, 0.0131, 0.0111, 0.0172, 0.0178, 0.0203, 0.0491, 0.0553, 0.0452, 0.0480, 0.0473, 0.0536, 0.0584],
  [0.0362, 0.0370, 0.0382, 0.0368, 0.0354, 0.0563, 0.0629, 0.0513, 0.0468, 0.0361, 0.0241, 0.0306, 0.0332, 0.0330, 0.0340, 0.0330, 0.0418, 0.0558, 0.0649, 0.0507, 0.0446, 0.0384, 0.0392, 0.0397],
  [0.0160, 0.0167, 0.0166, 0.0170, 0.0165, 0.0520, 0.0489, 0.0480, 0.0586, 0.0527, 0.0320, 0.0450, 0.0534, 0.0549, 0.0508, 0.0481, 0.0633, 0.0624, 0.0745, 0.0562, 0.0412, 0.0296, 0.0248, 0.0210],
  [0.0235, 0.0212, 0.0210, 0.0215, 0.0215, 0.0381, 0.0375, 0.0431, 0.0603, 0.0492, 0.0385, 0.0462, 0.0598, 0.0452, 0.0381, 0.0544, 0.0472, 0.0645, 0.0794, 0.0568, 0.0404, 0.0351, 0.0308, 0.0264],
  [0.0247, 0.0247, 0.0239, 0.0241, 0.0228, 0.0268, 0.0281, 0.0449, 0.0551, 0.0513, 0.0426, 0.0440, 0.0444, 0.0438, 0.0429, 0.0508, 0.0496, 0.0644, 0.0754, 0.0631, 0.0487, 0.0420, 0.0344, 0.0275],
  [0.0279, 0.0273, 0.0278, 0.0258, 0.0273, 0.0271, 0.0282, 0.0347, 0.0459, 0.0481, 0.0407, 0.0467, 0.0538, 0.0465, 0.0484, 0.0429, 0.0394, 0.0712, 0.0679, 0.0588, 0.0500, 0.0417, 0.0374, 0.0343],
  [0.0289, 0.0267, 0.0301, 0.0299, 0.0294, 0.0326, 0.0476, 0.0441, 0.0503, 0.0389, 0.0389, 0.0448, 0.0496, 0.0465, 0.0447, 0.0387, 0.0430, 0.0655, 0.0681, 0.0520, 0.0444, 0.0412, 0.0338, 0.0305],
  [0.0381, 0.0431, 0.0440, 0.0425, 0.0465, 0.0522, 0.0870, 0.0776, 0.0483, 0.0206, 0.0130, 0.0108, 0.0106, 0.0028, 0.0084, 0.0230, 0.0346, 0.0654, 0.0911, 0.0679, 0.0509, 0.0412, 0.0401, 0.0402],
  [0.0426, 0.0427, 0.0428, 0.0445, 0.0472, 0.0506, 0.0594, 0.0575, 0.0472, 0.0318, 0.0237, 0.0214, 0.0221, 0.0226, 0.0305, 0.0427, 0.0617, 0.0631, 0.0490, 0.0407, 0.0397, 0.0350, 0.0383, 0.0432],
  [0.0468, 0.0472, 0.0515, 0.0478, 0.0474, 0.0505, 0.0525, 0.0487, 0.0404, 0.0360, 0.0308, 0.0290, 0.0261, 0.0277, 0.0331, 0.0414, 0.0504, 0.0511, 0.0454, 0.0359, 0.0363, 0.0365, 0.0415, 0.0459],
];
