import * as fs from 'node:fs';
import * as path from 'node:path';
import * as readline from 'node:readline';

const csvPath = process.argv[2];
if (!csvPath) {
  console.error('Usage: npx tsx scripts/tools/process-smhi-data.ts "<path-to-smhi-csv>"');
  process.exit(1);
}

const sums: { total: number; count: number }[][] = Array.from({ length: 12 }, () =>
  Array.from({ length: 24 }, () => ({ total: 0, count: 0 })),
);

const rl = readline.createInterface({
  input: fs.createReadStream(csvPath),
  crlfDelay: Infinity,
});

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

rl.on('line', (line) => {
  const parts = line.split(';');
  const dateStr = parts[0]?.trim();
  if (!dateStr || !DATE_RE.test(dateStr)) return;

  const timeStr = parts[1]?.trim() ?? '';
  const ghiStr = parts[2]?.trim() ?? '';
  const quality = parts[3]?.trim();

  if (quality !== 'G') return;

  const ghi = parseFloat(ghiStr);
  if (isNaN(ghi)) return;

  const month = parseInt(dateStr.slice(5, 7), 10) - 1; // 0-indexed
  const hourUtc = parseInt(timeStr.slice(0, 2), 10);

  if (month < 0 || month > 11 || hourUtc < 0 || hourUtc > 23) return;

  sums[month][hourUtc].total += ghi;
  sums[month][hourUtc].count += 1;
});

rl.on('close', () => {
  const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  const avgGhiByMonthHour = sums.map((monthSums) =>
    monthSums.map(({ total, count }) =>
      count > 0 ? Math.round((total / count) * 10) / 10 : 0,
    ),
  );

  const avgDailyGhiByMonth = avgGhiByMonthHour.map((hours) =>
    Math.round(hours.reduce((s, v) => s + v, 0) * 10) / 10,
  );

  const lines: string[] = [
    '// Generated by scripts/tools/process-smhi-data.ts — do not edit by hand',
    '// Source: SMHI station Göteborg Sol (71415), 1983–2026, quality G (validated) only',
    '// avgGhiByMonthHour[month-1][hourUtc] = average Global Horizontal Irradiance (W/m²)',
    '',
    'export const avgGhiByMonthHour: number[][] = [',
    ...avgGhiByMonthHour.map((hours, mi) => `  [${hours.join(', ')}], // ${MONTH_NAMES[mi]}`),
    '];',
    '',
    '// Average daily GHI total (Wh/m²/day) by month',
    `export const avgDailyGhiByMonth: number[] = [${avgDailyGhiByMonth.join(', ')}];`,
    `// Months: ${MONTH_NAMES.join(', ')}`,
    '',
  ];

  const outPath = path.join(process.cwd(), 'lib', 'irradiance-data.ts');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

  console.log(`Written: ${outPath}`);
  console.log(`\nSanity checks:`);
  console.log(`  Jun UTC 10 (≈ noon Stockholm):  ${avgGhiByMonthHour[5][10]} W/m²  (expect ~300–600)`);
  console.log(`  Dec UTC 11 (≈ noon Stockholm):  ${avgGhiByMonthHour[11][11]} W/m²  (expect ~20–80)`);
  console.log(`  Jun daily total: ${avgDailyGhiByMonth[5]} Wh/m²/day  (expect ~4000–6000)`);
  console.log(`  Dec daily total: ${avgDailyGhiByMonth[11]} Wh/m²/day  (expect ~200–500)`);
});
