// Computes solarCalibrationByMonth: the ratio between your own measured solar production
// (avgDailyProductionByMonth, generated by scripts/process-inverter-data.ts from your own
// inverter export) and the raw, UNcalibrated GHI-model estimate for the same months (your
// site's climatology in lib/irradiance-data.ts, run through the exact ghiToKwh() formula the
// live app uses — imported, not reimplemented, so this can never silently drift from what
// getSolarProfileByMonth() actually computes at runtime).
//
// This is the missing half of the solar-forecast calibration pipeline: lib/solar.ts already
// multiplies ghiToKwh()'s output by solarCalibrationByMonth, but nothing in the repo computed
// that ratio until now — it was derived by hand for this installation. Run this whenever you
// (re)generate avgDailyProductionByMonth for a new site, so the calibration reflects that
// site's own panels/roof/shading rather than someone else's.
//
// Usage: npx tsx scripts/build-solar-calibration.ts
// Reads:  lib/consumption-data.ts's avgDailyProductionByMonth (regenerate first via
//         process-inverter-data.ts if you haven't already — this script is meaningless
//         against another site's production numbers)
//         lib/irradiance-data.ts's avgGhiByMonthHour (regenerate via process-smhi-data.ts,
//         or an equivalent climatology source, for your own location first)
//         lib/constants.ts's SOLAR_ARRAYS (your panel kWp/tilt/azimuth/performanceRatio)
// Prints: TypeScript-ready solarCalibrationByMonth to paste into lib/consumption-data.ts.
//
// A fresh site with zero production history yet has nothing to calibrate against — see
// DOMAIN.md's "Adapting to a new site" section for the full onboarding order and what to ship
// as a neutral placeholder (all 1.0) until real data exists.

import { avgGhiByMonthHour } from '../lib/irradiance-data';
import { avgDailyProductionByMonth } from '../lib/consumption-data';
import { ghiToKwh } from '../lib/solar';

const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const r2 = (n: number) => Math.round(n * 100) / 100;

const rawEstimateByMonth = avgGhiByMonthHour.map((hours) =>
  r2(hours.reduce((sum, ghi) => sum + ghiToKwh(ghi), 0)),
);

console.log('Solar-model calibration (measured production ÷ raw GHI-model estimate)\n');
console.log('Month  Measured  Raw GHI-model  Ratio');
console.log('─────  ────────  ─────────────  ─────');

const ratios = rawEstimateByMonth.map((raw, i) => {
  const measured = avgDailyProductionByMonth[i] ?? 0;
  const ratio = raw > 0 ? r2(measured / raw) : 1;
  console.log(
    `${MONTH_NAMES[i].padEnd(5)}  ${String(measured).padStart(8)}  ${String(raw).padStart(13)}  ${String(ratio).padStart(5)}`,
  );
  return ratio;
});

if (avgDailyProductionByMonth.every((v) => v === 0)) {
  console.warn(
    '\nWarning: avgDailyProductionByMonth is all zeros — regenerate it first via ' +
      'process-inverter-data.ts against your own production data before trusting this output.',
  );
}

console.log('\n\n// ── Paste into lib/consumption-data.ts ──────────────────────────────');
console.log(
  `// Ratio of actual daily production to the GHI-based model estimate, by month.\n` +
    `// Generated by scripts/build-solar-calibration.ts from avgDailyProductionByMonth above\n` +
    `// and lib/irradiance-data.ts's climatology.\n` +
    `export const solarCalibrationByMonth: number[] = ${JSON.stringify(ratios)};`,
);
